version: '3'
services:
  robot:
    env_file: .env
    container_name: ${robot_container_name}
    build:
      context: .
      dockerfile: RFW/Dockerfile
    image: ${robot_image_name}
    volumes:
      - /home/robot/${robot_result_folder}:/robotframework-databaselibrary-1.0.1
    networks:
      frontend:
        aliases:
          - robotsever
    depends_on:
      - cpservice
    command: >
      /bin/bash -c "
        /run.sh
        "
  jboss:
    env_file: .env
    container_name: ${jboss_container_name}
    build:
      context: .
      dockerfile: Dockerfile
    image: ${jboss_image_name}

